window.HORECA_CATALOG = {
  "version": 1,
  "products": [
    {
      "category": "Вода",
      "subcategory": "С газом",
      "name": "Вода газ. 0.25 л ПЭТ",
      "brand": "Черноголовка",
      "volume": 0.25,
      "package": 24,
      "price": 10,
      "image": "assets/img/products/Черноголовка__Вода_газ_0_25_л_ПЭТ-8969a574.jpg",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Нет",
      "sort": 5,
      "description": "",
      "box_price": 240.0
    },
    {
      "category": "Вода",
      "subcategory": "Без газа",
      "name": "Вода негаз. 0.25 л ПЭТ",
      "brand": "Черноголовка",
      "volume": 0.25,
      "package": 24,
      "price": 10,
      "image": "assets/img/products/Черноголовка__Вода_негаз_0_25_л_ПЭТ-1921db99.jpg",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Нет",
      "sort": 5,
      "description": "",
      "box_price": 240.0
    },
    {
      "category": "Вода",
      "subcategory": "С газом",
      "name": "Вода газ. 0.5 л ПЭТ",
      "brand": "Черноголовка",
      "volume": 0.5,
      "package": 12,
      "price": 10,
      "image": "assets/img/products/Черноголовка__Вода_газ_0_5_л_ПЭТ-e9b39cf4.jpg",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Да",
      "sort": 3,
      "description": "",
      "box_price": 120.0
    },
    {
      "category": "Вода",
      "subcategory": "Без газа",
      "name": "Вода негаз. 0.5 л ПЭТ",
      "brand": "Черноголовка",
      "volume": 0.5,
      "package": 12,
      "price": 10,
      "image": "assets/img/products/Черноголовка__Вода_негаз_0_5_л_ПЭТ-89091bcd.jpg",
      "status": "В наличие",
      "hit": "Нет",
      "premium": "Да",
      "sort": 4,
      "description": "",
      "box_price": 120.0
    },
    {
      "category": "Вода",
      "subcategory": "С газом",
      "name": "Вода газ. 0.5 л Стекло",
      "brand": "Черноголовка",
      "volume": 0.5,
      "package": 12,
      "price": 10,
      "image": "assets/img/products/Черноголовка__Вода_газ_0_5_л_Стекло-8e665ad0.jpg",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Да",
      "sort": 3,
      "description": "",
      "box_price": 120.0
    },
    {
      "category": "Вода",
      "subcategory": "Без газа",
      "name": "Вода негаз. 0.5 л Стекло",
      "brand": "Черноголовка",
      "volume": 0.5,
      "package": 12,
      "price": 10,
      "image": "assets/img/products/Черноголовка__Вода_негаз_0_5_л_Стекло-5ceb6c03.jpg",
      "status": "В наличие",
      "hit": "Нет",
      "premium": "Да",
      "sort": 4,
      "description": "",
      "box_price": 120.0
    },
    {
      "category": "Вода",
      "subcategory": "С газом",
      "name": "Вода газ. 0.33 л Стекло",
      "brand": "Черноголовка",
      "volume": 0.33,
      "package": 12,
      "price": 10,
      "image": "assets/img/products/Черноголовка__Вода_газ_0_33_л_Стекло-95ba4d1f.jpg",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Да",
      "sort": 3,
      "description": "",
      "box_price": 120.0
    },
    {
      "category": "Вода",
      "subcategory": "Без газа",
      "name": "Вода негаз. 0.33 л Стекло",
      "brand": "Черноголовка",
      "volume": 0.33,
      "package": 12,
      "price": 10,
      "image": "assets/img/products/Черноголовка__Вода_негаз_0_33_л_Стекло-9c75a452.jpg",
      "status": "В наличие",
      "hit": "Нет",
      "premium": "Да",
      "sort": 4,
      "description": "",
      "box_price": 120.0
    },
    {
      "category": "Вода",
      "subcategory": "С газом",
      "name": "Вода газ. 0.5 л ПЭТ",
      "brand": "Bona aqua",
      "volume": 0.5,
      "package": 24,
      "price": 10,
      "image": "assets/img/products/Bona_aqua_Вода_газ_0_5_л_ПЭТ-ac174157.jpg",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Нет",
      "sort": 6,
      "description": "",
      "box_price": 240.0
    },
    {
      "category": "Вода",
      "subcategory": "Без газа",
      "name": "Вода негаз. 0.5 л ПЭТ",
      "brand": "Bona aqua",
      "volume": 0.5,
      "package": 24,
      "price": 10,
      "image": "assets/img/products/Bona_aqua_Вода_негаз_0_5_л_ПЭТ-7ac404fc.jpg",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Нет",
      "sort": 7,
      "description": "",
      "box_price": 240.0
    },
    {
      "category": "Вода",
      "subcategory": "Без газа",
      "name": "Вода негаз. 1 л ПЭТ",
      "brand": "Bona aqua",
      "volume": 1,
      "package": 12,
      "price": 10,
      "image": "assets/img/products/Bona_aqua__Вода_негаз_1_л_ПЭТ-58dd4f64.jpg",
      "status": "В наличие",
      "hit": "Нет",
      "premium": "Да",
      "sort": 8,
      "description": "",
      "box_price": 120.0
    },
    {
      "category": "Вода",
      "subcategory": "С газом",
      "name": "Вода газ. 1 л ПЭТ",
      "brand": "Bona aqua",
      "volume": 1,
      "package": 12,
      "price": 10,
      "image": "assets/img/products/Bona_aqua_Вода_газ_1_л_ПЭТ-d29730c1.jpg",
      "status": "В наличие",
      "hit": "Нет",
      "premium": "Да",
      "sort": 9,
      "description": "",
      "box_price": 120.0
    },
    {
      "category": "Вода",
      "subcategory": "Без газа",
      "name": "Вода негаз. 0.5 л ПЭТ",
      "brand": "Святой Источник",
      "volume": 0.5,
      "package": 12,
      "price": 10,
      "image": "assets/img/products/Святой_Источник_Вода_негаз_0_5_л_ПЭТ-ddefb2c2.jpg",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Да",
      "sort": 10,
      "description": "",
      "box_price": 120.0
    },
    {
      "category": "Вода",
      "subcategory": "С газом",
      "name": "Вода газ. 0.5 л ПЭТ",
      "brand": "Святой Источник",
      "volume": 0.5,
      "package": 12,
      "price": 10,
      "image": "assets/img/products/Святой_Источник_Вода_газ_0_5_л_ПЭТ-943101d1.jpg",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Да",
      "sort": 11,
      "description": "",
      "box_price": 120.0
    },
    {
      "category": "Вода",
      "subcategory": "Без газа",
      "name": "Вода негаз. 1 л ПЭТ",
      "brand": "Святой Источник",
      "volume": 1,
      "package": 12,
      "price": 10,
      "image": "assets/img/products/Святой_Источник_Вода_негаз_1_л_ПЭТ-641dee06.jpg",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Да",
      "sort": 10,
      "description": "",
      "box_price": 120.0
    },
    {
      "category": "Вода",
      "subcategory": "С газом",
      "name": "Вода газ. 1 л ПЭТ",
      "brand": "Святой Источник",
      "volume": 1,
      "package": 12,
      "price": 10,
      "image": "assets/img/products/Святой_Источник_Вода_газ_1_л_ПЭТ-47d111c7.jpg",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Да",
      "sort": 11,
      "description": "",
      "box_price": 120.0
    },
    {
      "category": "Вода",
      "subcategory": "С газом",
      "name": "Вода газ. 0.33 л ПЭТ",
      "brand": "Святой Источник",
      "volume": 0.33,
      "package": 12,
      "price": 10,
      "image": "assets/img/products/Святой_Источник_Вода_газ_0_33_л_ПЭТ-0fc5ce58.jpg",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Да",
      "sort": 11,
      "description": "",
      "box_price": 120.0
    },
    {
      "category": "Вода",
      "subcategory": "Без газа",
      "name": "Вода негаз. 0.33 л ПЭТ",
      "brand": "Святой Источник",
      "volume": 0.33,
      "package": 12,
      "price": 10,
      "image": "assets/img/products/Святой_Источник_Вода_негаз_0_33_л_ПЭТ-75ffd30e.jpg",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Да",
      "sort": 11,
      "description": "",
      "box_price": 120.0
    }
  ]
};
