window.HORECA_CATALOG = {
  "version": 1,
  "products": [
    {
      "category": "Вода",
      "name": "CRISTELLE питьевая вода негаз 0.33 л Стекло",
      "brand": "Cristelle",
      "volume": 0.33,
      "package": 24,
      "price": 10,
      "image": "https://disk.yandex.ru/i/kRH3sWjGmfgIwA",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Нет",
      "sort": 1,
      "description": "",
      "box_price": 240.0
    },
    {
      "category": "Вода",
      "name": "CRISTELLE питьевая вода негаз 0.75 л Стекло",
      "brand": "Cristelle",
      "volume": 0.75,
      "package": 24,
      "price": 11,
      "image": "https://disk.yandex.ru/i/Q2AtFjNxgUiDgQ",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Нет",
      "sort": 2,
      "description": "",
      "box_price": 264.0
    },
    {
      "category": "Вода",
      "name": "Вода минеральная питьевая Черноголовка негаз. 0.33 л Стекло",
      "brand": "Черноголовка",
      "volume": 0.33,
      "package": 12,
      "price": 12,
      "image": "https://disk.yandex.ru/i/s76QrodTurxqoA",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Да",
      "sort": 3,
      "description": "",
      "box_price": 144.0
    },
    {
      "category": "Вода",
      "name": "Вода минеральная питьевая Черноголовка негаз. 0.5 л Стекло",
      "brand": "Черноголовка",
      "volume": 0.5,
      "package": 12,
      "price": 13,
      "image": "https://disk.yandex.ru/i/1By5PutprcsWvA",
      "status": "В наличие",
      "hit": "Нет",
      "premium": "Да",
      "sort": 4,
      "description": "",
      "box_price": 156.0
    },
    {
      "category": "Вода",
      "name": "Вода Черноголовка негаз. 0.25 л ПЭТ",
      "brand": "Черноголовка",
      "volume": 0.25,
      "package": 24,
      "price": 14,
      "image": "https://disk.yandex.ru/i/tLBrBrEaMHtoKA",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Нет",
      "sort": 5,
      "description": "",
      "box_price": 336.0
    },
    {
      "category": "Вода",
      "name": "Бона Аква Вода негаз. 0.5 л ПЭТ",
      "brand": "Bona aqua",
      "volume": 0.5,
      "package": 12,
      "price": 15,
      "image": "https://disk.yandex.ru/i/K0YA92yyNyjzMg",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Нет",
      "sort": 6,
      "description": "",
      "box_price": 180.0
    },
    {
      "category": "Вода",
      "name": "Бона Аква Вода негаз. 1 л ПЭТ",
      "brand": "Bona aqua",
      "volume": 1,
      "package": 12,
      "price": 16,
      "image": "https://disk.yandex.ru/i/qQG6vvRLCdG-bg",
      "status": "В наличие",
      "hit": "Нет",
      "premium": "Да",
      "sort": 7,
      "description": "",
      "box_price": 192.0
    },
    {
      "category": "Вода",
      "name": "Святой источник вода негаз. 0.5 л ПЭТ",
      "brand": "Святой Источник",
      "volume": 0.5,
      "package": 12,
      "price": 17,
      "image": "https://disk.yandex.ru/i/YNFKZaBx5ae-gg",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Да",
      "sort": 8,
      "description": "",
      "box_price": 204.0
    }
  ]
};
