window.HORECA_CATALOG = {
  "version": 1,
  "products": [
    {
      "category": "Вода",
      "name": "CRISTELLE питьевая вода негаз 0.33 л Стекло",
      "brand": "Cristelle",
      "volume": 0.33,
      "package": 24,
      "price": 10,
      "image": "assets/img/products/Cristelle_CRISTELLE_питьевая_вода_негаз_0_33_л_Стекло-ddb9fdca.png",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Нет",
      "sort": 1,
      "description": "",
      "box_price": 240.0
    },
    {
      "category": "Вода",
      "name": "CRISTELLE питьевая вода негаз 0.75 л Стекло",
      "brand": "Cristelle",
      "volume": 0.75,
      "package": 24,
      "price": 11,
      "image": "assets/img/products/Cristelle__CRISTELLE_питьевая_вода_негаз_0_75_л_Стекло-df0fd0a8.png",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Нет",
      "sort": 2,
      "description": "",
      "box_price": 264.0
    },
    {
      "category": "Вода",
      "name": "Вода минеральная питьевая Черноголовка негаз. 0.33 л Стекло",
      "brand": "Черноголовка",
      "volume": 0.33,
      "package": 12,
      "price": 12,
      "image": "assets/img/products/Черноголовка__Вода_минеральная_питьевая_Черноголовка_негаз_0_33_л_Стекло-b85f0786.png",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Да",
      "sort": 3,
      "description": "",
      "box_price": 144.0
    },
    {
      "category": "Вода",
      "name": "Вода минеральная питьевая Черноголовка негаз. 0.5 л Стекло",
      "brand": "Черноголовка",
      "volume": 0.5,
      "package": 12,
      "price": 13,
      "image": "assets/img/products/Черноголовка_Вода_минеральная_питьевая_Черноголовка_негаз_0_5_л_Стекло-42e70186.png",
      "status": "В наличие",
      "hit": "Нет",
      "premium": "Да",
      "sort": 4,
      "description": "",
      "box_price": 156.0
    },
    {
      "category": "Вода",
      "name": "Вода Черноголовка негаз. 0.25 л ПЭТ",
      "brand": "Черноголовка",
      "volume": 0.25,
      "package": 24,
      "price": 14,
      "image": "assets/img/products/Черноголовка__Вода_Черноголовка_негаз_0_25_л_ПЭТ-18342324.png",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Нет",
      "sort": 5,
      "description": "",
      "box_price": 336.0
    },
    {
      "category": "Вода",
      "name": "Бона Аква Вода негаз. 0.5 л ПЭТ",
      "brand": "Bona aqua",
      "volume": 0.5,
      "package": 12,
      "price": 15,
      "image": "assets/img/products/Bona_aqua_Бона_Аква_Вода_негаз_0_5_л_ПЭТ-8e481726.png",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Нет",
      "sort": 6,
      "description": "",
      "box_price": 180.0
    },
    {
      "category": "Вода",
      "name": "Бона Аква Вода негаз. 1 л ПЭТ",
      "brand": "Bona aqua",
      "volume": 1,
      "package": 12,
      "price": 16,
      "image": "assets/img/products/Bona_aqua__Бона_Аква_Вода_негаз_1_л_ПЭТ-006031dc.png",
      "status": "В наличие",
      "hit": "Нет",
      "premium": "Да",
      "sort": 7,
      "description": "",
      "box_price": 192.0
    },
    {
      "category": "Вода",
      "name": "Святой источник вода негаз. 0.5 л ПЭТ",
      "brand": "Святой Источник",
      "volume": 0.5,
      "package": 12,
      "price": 17,
      "image": "assets/img/products/Святой_Источник_Святой_источник_вода_негаз_0_5_л_ПЭТ-17af6005.png",
      "status": "В наличие",
      "hit": "Да",
      "premium": "Да",
      "sort": 8,
      "description": "",
      "box_price": 204.0
    }
  ]
};
